version: 2
experimental:
  notify:
    branches:
      only:
        - master
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/keenethics
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn deploy
