version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11
    working_directory: ~/keenethics
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Fix host authenticity for 107.170.121.178
          command: ssh-keyscan 107.170.121.178 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "b5:cb:91:30:e3:4c:b0:ab:56:9c:29:a0:34:9a:ab:2d"
      - run: yarn deploy
